// Triangular, pentagonal, and hexagonal

// Problem 45
// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
// Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.

// Find the next triangle number that is also pentagonal and hexagonal.

const shapes = require('../../util/shapes');

function getTrianglePentagonHexagon() {
  let limit = 2000000000,
    // no need to store triangles because all hexagons are also triangular
    pentagons = shapes.getPentagons(limit),
    hexagons = shapes.getHexagons(limit),
    pentagonKeys = Object.keys(pentagons),
    start = pentagonKeys.indexOf('40755') + 1;

  for (let i = start; i < pentagonKeys.length; i++) {
    let pkey = pentagonKeys[i];
    if (hexagons[pkey]) {
      return pkey;
    }
  }

  return `unable to find the next triangle number that is also pentagonal and hexagonal under ${limit}`;
}

module.exports = getTrianglePentagonHexagon;
