# Triangular, pentagonal, and hexagonal

# Problem 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

from ...util import shapes


def get_triangle_pentagon_hexagon():
  n = 144

  while shapes.is_pentagonal(shapes.get_nth_hexagon(n), None) == False:
    n += 1

  return shapes.get_nth_hexagon(n)