const getDistinctTermCount = require('./question-029');

test('gets the count of distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100 to be 9,183', () => {
  expect(getDistinctTermCount()).toBe(9183);
});
