const getDistinctTermCount = require(`./question-029`);

test(`gets the count of distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5 to be 15`, () => {
  expect(getDistinctTermCount(5)).toBe(15);
});

test(`gets the count of distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100 to be 9,183`, () => {
  expect(getDistinctTermCount(100)).toBe(9183);
});
